# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:35
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160727_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='geolocation',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
