# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160727_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
