# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160804_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debate',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
        migrations.AlterField(
            model_name='debate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='debate',
            name='debate_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='debate_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
