# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160807_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='body',
            new_name='checkin_body',
        ),
        migrations.RenameField(
            model_name='debate',
            old_name='body',
            new_name='debate_body',
        ),
    ]
