# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160730_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos', verbose_name='Profile Photo'),
        ),
    ]
