# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160801_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
