# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checkin_type',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football')], default='Football', max_length=30),
        ),
    ]
