# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_checkin_checkin_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
