# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20160803_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=100, null=True)),
                ('debate_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
                ('debate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CheckIn')),
                ('debate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
