# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_debate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='debate_type',
        ),
    ]
